# -*- coding: utf-8 -*-
"""Запрос.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1veEsnO0X0MUguN_VSOdxyzHN8tp0t28Y
"""

bins = [
    '004443', '220005', '220006', '220009', '220012',
    '220013', '220014', '220016', '220018', '220022',
    '220031', '220032', '220033', '220037', '220043'
]

import requests

url = "https://bin-ip-checker.p.rapidapi.com/"
headers = {
	"content-type": "application/json",
	"X-RapidAPI-Key": "ab8b8c83d5msh780e2bc27db536cp1df682jsn76db90722239",
	"X-RapidAPI-Host": "bin-ip-checker.p.rapidapi.com"
}
result = ''

for bin in bins:
  
  payload = {"bin": bin}
  print(payload)
  response = json.loads((requests.request("POST", url, json=payload, headers=headers, params=payload)).text)

  if(response['code']==200 and response['BIN']['issuer']['name'] != '' ):
    bank = response['BIN']['issuer']['name']
    country = response['BIN']['country'][ 'alpha2']
  else:
    continue

  result =  result +'insert into banks(bin, name, country) values('+bin+',\''+bank+'\',\''+country+'\'),\n'
  
print(result)

ls

from google.colab import files
f = open('banks_new.txt', 'w')
f.write(result)
f.close()
files.download('banks.txt')

"""### //Запасной вариант"""

import requests
import json

bins = ['004443','220005','220006','220009']
url = 'https://bincheck.io/ru/details/'
bin_inforation_array = ''

for bin in bins:
  page_text = requests.get(url+bin).text

  comment_index = page_text.find('Same Country BINs')
  index_data = page_text.find('data:', comment_index)
  index_success = page_text.find('},', index_data)
  data = page_text[index_data:index_success+1]
  data = data.replace('data:', '')
  data = data.replace('issuer_name', '"issuer_name"')
  data = data.replace('country_name', '"country_name"')
  data = data.replace('\'', '"')

  data = json.loads(data)
  bank = data['issuer_name']
  country = data['country_name']

  if(bank == ''):
    continue
  else:
    result = 'insert into banks(bin, name, country) values('+bin+',\''+bank+'\',\''+country+'\'),\n'
    bin_inforation_array = bin_inforation_array + result
    
print(bin_inforation_array)
